/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIClass */

#ifndef _Included_JNIClass
#define _Included_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIClass
 * Method:    getProcInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIClass_getProcInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
